---
title: "dplyr and pandas"
author: by Nicolas Lange Machado

output:
    html_document:
        toc: true

---
## Data
```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(knitr)
```
```{r, echo = FALSE}
df <- mtcars %>% head(5)
df <- cbind(Model = rownames(df), df)
rownames(df) <- NULL
kable(df)

```


## Select {.tabset}
### R
```{r, eval = FALSE}
df %>% select(mpg,cyl,disp,hp,drat,wt)
# or alternatively
df %>% select(-qsec, -vs, -am, -gear, -carb)
```

### Python
```{r, eval = FALSE}
df[['mpg','cyl','disp','hp','drat','wt']]
# or alternatively
df.drop(['qsec', 'vs', 'am', 'gear', 'carb'], axis = 1)
```
### Output
```{r, echo = FALSE}
kable(df %>% select(mpg,cyl,disp,hp,drat,wt))
```





## Filter {.tabset}
### R
```{r, eval = FALSE}
df %>% filter(hp >= 110 & carb <= 3)

```

### Python
```{r, eval = FALSE}
df[['mpg','cyl','disp','hp','drat','wt']]
# or alternatively
df.drop(['qsec', 'vs', 'am', 'gear', 'carb'], axis = 1)
```
### Output
```{r, echo = FALSE}
kable(df %>% filter(hp >= 110 & carb <= 3))
```